---
sudo: required
dist: trusty
language: python
env:
  - COPR_PROJECT="marknexcess/mg"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm wget
  - mkdir -p BUILD RPMS SOURCES SPECS SRPMS
  - openssl aes-256-cbc -K $encrypted_dccc5e4cac06_key -iv $encrypted_dccc5e4cac06_iv -in .copr.enc -out .copr -d
install: pip install copr copr-cli
script:
  - rpmspec -P  SPECS/mg.spec | awk '/^Source/ {print $2}' | xargs -n1 wget -P SOURCES
  - rpmbuild -bs --define '_topdir ./' SPECS/*spec
  - copr-cli --config .copr build ${COPR_PROJECT} SRPMS/*src.rpm --nowait
notifications:
  email:
    on_success: never
    on_failure: always
