---
sudo: required
language: bash
services:
  - docker
before_install:
  - docker pull mmckinst/rpmbuilder
env:
  - MOCK_CONFIG="epel-6-i386"
  - MOCK_CONFIG="epel-6-x86_64"
  - MOCK_CONFIG="epel-7-x86_64"
script:
  - docker run -e MOCK_CONFIG="${MOCK_CONFIG}" -v "$(pwd):/rpmbuild" --privileged=true mmckinst/rpmbuilder
notifications:
  email:
    on_success: never
    on_failure: always
